# -*- coding: utf-8 -*-
"""Safety_Helmet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BbtCzitvKiVT85CDWTZZwQ7vg4cyED6n
"""

from google.colab import drive
drive.mount("/content/gdrive",force_remount=True)

cd /content/gdrive/MyDrive

cd Project

!pip install ultralytics

from ultralytics import YOLO

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="jvaSOwSiBXoLqGrheuql")
project = rf.workspace("20-tcltq").project("safety-helmet-xdnwb")
dataset = project.version(5).download("yolov8")

!yolo task=detect model=yolov8s.pt data=/content/gdrive/MyDrive/Project/safety-helmet--5/data.yaml epochs=100 imgsz=640

